Support Rails v6.0 document (#74)
* Create collections

ref. https://jekyllrb.com/docs/step-by-step/09-collections/

* Define collections

* Create mkdir rake task

* Add: switch_rails method

* Define specific_version under version

* Enhance switch_rails

* mkdir && switch_rails

* Update submodule: v6.0.3

* Set frozen_string_literal

* Change collection config format

ref. https://jekyllrb.com/docs/step-by-step/09-collections/

* Use just each

* Float to String

```
jekyll/collection.rb:163:in `sanitize_label': undefined method `gsub' for 6.0:Float (NoMethodError)
```

* Create version directory inside src

* Add: generate_rails_rdoc, generate_src

* Add target_version to generate_src

* Define INDEX_HTML

* mv navigation.html

* collections→rails_versions

* main: Rails v6, sub: Rails v5

* Create build_multi task

* Set scope for Rails 5.2 path

* Change navigation path

* Replace link path

* Replace path

* Add files for Rails v5.2

* Bump bootstrap from 4.5 to 4.6

ref. https://getbootstrap.com/docs/4.6/getting-started/introduction/

* Set navbar-expand to header

* Display version selector

* target_rails_version→default_rails_version

* Add doc-build to CI

* Add require

* Create symbolic link for default version

* Set default page.version

* checkout with submodule

* Use macOS for doc build

* Bump rails: 6.0.3→6.0.3.6

* sed shell script → ruby File read/write

to make it OS-agnostic

* Revert "Use macOS for doc build"

This reverts commit 895c0d29238aa9348f27775b16788012eeb62e77.

* switch_default_rails→build

* Revert "switch_default_rails→build"

This reverts commit 3eb87b870aa24b122c0fb4c9391b86900fa165fc.

* Update ci.yml

* Generate Rails v6.0 doc